apiVersion: v1
kind: Service
metadata:
  name: kube-resourceless
  namespace: kube-resourceless
  labels:
    app: kube-resourceless
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
  selector:
    app: kube-resourceless