name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  GO111MODULE: on
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.21.x
    - uses: actions/checkout@v2
    - name: Build sources
      run: go build ./...
    - name: Run tests
      run: make test
